name: "Unoffical MeshMonitor HA app"
version: "0.0.5"
slug: "unoffical_meshmonitor_ha_app"
description: >-
  Simple Home Assistant app wrapper for MeshMonitor using a TCP/IP Meshtastic node.
url: "https://github.com/Yeraze/meshmonitor"
startup: application
boot: auto
init: false
arch:
  - amd64
  - aarch64
  - armv7

webui: "http://[HOST]:[PORT:3001]"

ports:
  3001/tcp: 8080
  4404/tcp: 4404

ports_description:
  3001/tcp: "MeshMonitor web interface"
  4404/tcp: "Virtual Node Server (Meshtastic mobile app TCP)"

options:
  node_ip: "192.168.1.100"
  node_tcp_port: 4403
  timezone: "Europe/Stockholm"
  trust_proxy: true
  cookie_secure: true
  allowed_origins: "*"

schema:
  node_ip: str
  node_tcp_port: port
  timezone: str
  trust_proxy: bool
  cookie_secure: bool
  allowed_origins: str
